<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>RILEY</title>
</head>

<body>
    <input type="button" value="查看消息" onclick="message()" />

    <hr>

    <p>请输出一个 5 到 10 之间的数字:</p>
    <input id="demo" type="text">
    <button type="button" onclick="myFunction()">测试输入</button>
    <p id="message"></p>
</body>

<script>
    var txt = "";
    function message() {
        try {
            adddlert("Welcome guest!");
        }
        catch (err) {
            txt = "本页有一个错误。\n\n";
            txt += "错误描述：" + err.message + "\n\n";
            txt += "点击确定继续。\n\n";
            alert(txt);
        }
    }

    function myFunction() {
        var message, x;
        message = document.getElementById("message");
        x = document.getElementById("demo").value;
        try {
            if (x == "") throw "值为空";
            if (isNaN(x)) throw "不是数字";
            x = Number(x);
            if (x < 5) throw "太小";
            if (x > 10) throw "太大";
            message.innerHTML = "正确";
        }
        catch (err) {
            message.innerHTML = "错误: " + err;
        }
        finally {
            document.getElementById("demo").value = "";
        }
    }

// try 语句测试代码块的错误。
// catch 语句处理错误。
// throw 语句创建自定义错误。
// finally 语句在 try 和 catch 语句之后，无论是否有触发异常，该语句都会执行。
</script>

</html>